SELECT TEMP.AUTHOR_ID, A.AUTHOR_NAME, TEMP.CATEGORY, SUM(TEMP.TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A JOIN (
SELECT B.AUTHOR_ID, B.CATEGORY, S.SALES * B.PRICE AS TOTAL_SALES
FROM BOOK B JOIN (
SELECT BOOK_ID, SALES
FROM BOOK_SALES
WHERE SALES_DATE LIKE '2022-01%') S
ON B.BOOK_ID = S.BOOK_ID ) TEMP
ON A.AUTHOR_ID = TEMP.AUTHOR_ID
GROUP BY TEMP.AUTHOR_ID, TEMP.CATEGORY
ORDER BY TEMP.AUTHOR_ID ASC, TEMP.CATEGORY DESC;