-- 코드를 입력하세요
SELECT TEMP.AUTHOR_ID, AUTHOR.AUTHOR_NAME, TEMP.CATEGORY, SUM(TEMP.TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR JOIN
(SELECT BOOK.AUTHOR_ID, BOOK.CATEGORY, SALE.SALES * BOOK.PRICE AS TOTAL_SALES
FROM BOOK JOIN
(SELECT BOOK_ID, SALES
FROM BOOK_SALES
WHERE SALES_DATE LIKE '2022-01%') AS SALE
ON BOOK.BOOK_ID = SALE.BOOK_ID) AS TEMP
ON AUTHOR.AUTHOR_ID = TEMP.AUTHOR_ID
GROUP BY TEMP.AUTHOR_ID, TEMP.CATEGORY
ORDER BY TEMP.AUTHOR_ID ASC, TEMP.CATEGORY DESC;