-- 코드를 작성해주세요
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME
FROM ITEM_INFO JOIN 
(SELECT *
FROM ITEM_TREE
WHERE PARENT_ITEM_ID IS NULL) T
ON ITEM_INFO.ITEM_ID = T.ITEM_ID
ORDER BY ITEM_INFO.ITEM_ID ASC;