-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS JOIN
(SELECT OUTS.ANIMAL_ID, DATEDIFF(OUTS.DATETIME, INS.DATETIME) AS DATEDIFFER
FROM ANIMAL_OUTS OUTS JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
ORDER BY DATEDIFFER DESC
LIMIT 2) AS A
ON ANIMAL_INS.ANIMAL_ID = A.ANIMAL_ID

