-- 코드를 작성해주세요
SELECT ID, 
(CASE 
WHEN (RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)) / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.25 THEN 'CRITICAL'
WHEN (RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)) / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.5 THEN 'HIGH'
WHEN (RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)) / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.75 THEN 'MEDIUM'
ELSE 'LOW' END) AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID



