-- 코드를 입력하세요
SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME, FIN.AMO * PRO.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT PRO JOIN 
(SELECT PRODUCT_ID, SUM(AMOUNT) AS AMO
FROM FOOD_ORDER 
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID) AS FIN
ON PRO.PRODUCT_ID = FIN.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRO.PRODUCT_ID ASC