-- 코드를 입력하세요
SELECT P.PRODUCT_ID, PRODUCT_NAME, PRICE * AMO AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN 
(SELECT PRODUCT_ID, SUM(AMOUNT) AS AMO
FROM FOOD_ORDER
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID) AP
ON P.PRODUCT_ID = AP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC