-- 코드를 입력하세요
SELECT JL.FLAVOR
FROM FIRST_HALF HAL JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT
FROM JULY
GROUP BY FLAVOR ) AS JL
ON HAL.FLAVOR = JL.FLAVOR
ORDER BY HAL.TOTAL_ORDER + JL.TOT DESC
LIMIT 3
