-- 코드를 입력하세요
SELECT TM.APNT_NO, TM.PT_NAME, TM.PT_NO, TM.MCDP_CD, D.DR_NAME, TM.APNT_YMD
FROM DOCTOR D JOIN 
(SELECT APNT_NO, PT_NAME, P.PT_NO, MCDP_CD, APNT_YMD, MDDR_ID
FROM PATIENT P JOIN (
SELECT *
FROM APPOINTMENT
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N'AND MCDP_CD = 'CS') AP
ON P.PT_NO = AP.PT_NO) TM
ON D.DR_ID = TM.MDDR_ID
ORDER BY APNT_YMD ASC