-- 코드를 입력하세요
SELECT TEMP_2.APNT_NO, PATIENT.PT_NAME, TEMP_2.PT_NO, TEMP_2.MCDP_CD, TEMP_2.DR_NAME, TEMP_2.APNT_YMD
FROM PATIENT RIGHT JOIN 
(SELECT TEMP.APNT_NO, TEMP.PT_NO, TEMP.MCDP_CD, DOCTOR.DR_NAME, TEMP.APNT_YMD
FROM DOCTOR RIGHT JOIN
(SELECT *
FROM APPOINTMENT 
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS') TEMP
ON DOCTOR.DR_ID = TEMP.MDDR_ID) TEMP_2
ON PATIENT.PT_NO = TEMP_2.PT_NO
ORDER BY TEMP_2.APNT_YMD ASC;