-- 코드를 입력하세요
SELECT P.MEMBER_NAME, TEMP.REVIEW_TEXT, DATE_FORMAT(TEMP.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P JOIN (
SELECT REST_REVIEW.MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW
WHERE MEMBER_ID = 
(SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(DISTINCT REVIEW_ID) DESC
LIMIT 1)) AS TEMP
ON P.MEMBER_ID = TEMP.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC