-- 코드를 입력하세요
SELECT PRO.MEMBER_NAME, REV.REVIEW_TEXT, DATE_FORMAT(REV.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE PRO JOIN REST_REVIEW REV
ON PRO.MEMBER_ID = REV.MEMBER_ID
WHERE PRO.MEMBER_ID = 
(SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(MEMBER_ID) DESC
LIMIT 1)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC