-- 코드를 입력하세요
SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN
(SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = '세단') C
ON H.CAR_ID = C.CAR_ID
WHERE H.START_DATE LIKE '%2022-10%'
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC;