-- 코드를 입력하세요
SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR JOIN
(SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-10%') AS RENTAL_10
ON CAR.CAR_ID = RENTAL_10.CAR_ID
WHERE CAR_TYPE = '세단'
ORDER BY CAR_ID DESC
