-- 코드를 작성해주세요
SELECT SCORE, HR.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES HR JOIN
(SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE 
GROUP BY EMP_NO) AS SUM_TABLE ON HR.EMP_NO = SUM_TABLE.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
