-- 코드를 작성해주세요
SELECT HR.DEPT_ID, HR.DEPT_NAME_EN, ROUND(AVGG,0) AS AVG_SAL
FROM HR_DEPARTMENT HR JOIN 
(SELECT DEPT_ID, AVG(SAL) AS AVGG
FROM HR_EMPLOYEES
GROUP BY DEPT_ID ) SAL_Q
ON HR.DEPT_ID = SAL_Q.DEPT_ID
ORDER BY AVG_SAL DESC