-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',F.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F JOIN 
(SELECT * 
FROM USED_GOODS_BOARD 
ORDER BY VIEWS DESC
LIMIT 1) T
ON F.BOARD_ID = T.BOARD_ID
ORDER BY FILE_ID DESC;
