-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK JOIN (
SELECT * 
FROM BOOK_SALES
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31') AS SALES
ON BOOK.BOOK_ID = SALES.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC
